name: 'Terraform Validate'

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Validate Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: '1.7.3'

      - name: 'Initialize Terraform'
        run: terraform init

      - name: 'Terraform Format'
        run: terraform fmt -check .

      - name: 'Validate Terraform'
        run: terraform validate
